#!/bin/bash

## Fill in name of program here.
PROG="XbmcSystemTools.py"
PROG_PATH="{{program_path}}"
PID_PATH="/var/run/"
SERVER_PORT="8092"

start() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        echo "Error! $PROG is already running!" 1>&2
        exit 1
    else
        python $PROG_PATH/$PROG $SERVER_PORT 2>&1 >/dev/null &
        echo "$PROG started"
        touch "$PID_PATH/$PROG.pid"
    fi
}

stop() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        killall $PROG
        killall python

        rm "$PID_PATH/$PROG.pid"

        echo "$PROG stopped"
    else
        echo "Couldn't stop service. $PROG is not running." 1>&2
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac